sudo: true

language: python

python:
  - 3.5

install:
  - pip3 install -r requirements.txt

script:
  - cd pyrgg
  - python3 test.py
  - cd ..
  - python3 setup.py install
after_success:
  - codecov