build: false

environment:
  matrix:
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.5.1"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "python setup.py install"

test_script:
  - "python -m pyrgg test"