build: false

environment:
  matrix:

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"



init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/python.exe setup.py install"
  - "%PYTHON%/python.exe -m pyrgg test"

test_script:
  - "%PYTHON%/Scripts/pip.exe install -r dev-requirements.txt"
  - "%PYTHON%/python.exe -m pytest pyrgg --cov=pyrgg --cov-report=term"
  